apiVersion: v1
kind: ConfigMap
metadata:
  name: linkloom-config
data:
  PORT: "3000"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/linkloom"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
