apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvbGlua2xvb20=
  FIRECRAWL_API_KEY: ZmMtNWFmNjFkMzM3ZGMwNDhjZjg0OWQ3YTVlZjFkYmI3ZjQ=
  OPENAI_API_KEY: c2stcHJvai03cFdZUkl1aWhRazNfM2VudmxwY2Z5aldOVDktZnZmVElJV3ZkcmhjRC15V2RYMlc3ZGNibFBDRC1JWTFNT0FXNDhKS3Qxbm5XU1QzQmxia0ZKYlBGUFNTMU9jMFZnVHlJcXFKOHhvbEFYUEVUaV9HcmpHdkJPajRxR1JlX1E5enltakhQQXVyNFFHemk2OEV1NWFHaFhQX2cxRUE=
  PORT: MzAwMA==
  POSTGRES_PASSWORD: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: null
  name: linkloom-secrets
